work directory

In [2]:
getwd()

[1] "c:/Users/M7600QE/Documents/arshad/Master-s-Coding/R/introductory/2_introduction"

```R
setwd("C:/Users/padide/Desktop")
```

In [3]:
x = 10
x

[1] 10

In [4]:
x <- 10
x

[1] 10

In [5]:
y <- 20
print(y)

[1] 20


class

In [6]:
class(x)

[1] "numeric"

In [7]:
x <- as.integer(x)
class(x)

[1] "integer"

In [8]:
y <- as.character(y)
y

[1] "20"

vector

In [9]:
d1 <- c(1,2,3,4,5)
d1

[1] 1 2 3 4 5

In [10]:
d2 <- c(6,7,8)
d2

[1] 6 7 8

In [11]:
d3 <- c(d1,d2)
d3

[1] 1 2 3 4 5 6 7 8

In [12]:
d4 <- c("Ali","Babak","Sara")
d4

[1] "Ali"   "Babak" "Sara"

In [13]:
d5 <- c(TRUE,FALSE)
d5

[1]  TRUE FALSE

In [14]:
d6 <- 1:10
d6

[1]  1  2  3  4  5  6  7  8  9 10

In [15]:
d7 <- seq(1,10, by =2)
d7

[1] 1 3 5 7 9

In [16]:
d8 <- seq(1,10, length = 4)
d8

[1]  1  4  7 10

In [17]:
d9 <- seq(1,10, length = 5)
d9

[1]  1.00  3.25  5.50  7.75 10.00

In [18]:
d10 <- rep (1, 5)
d10

[1] 1 1 1 1 1

In [19]:
d11 <- rep (1:3, 5)
d11

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [20]:
length(d11)

[1] 15

In [21]:
d11[4]

[1] 1

In [23]:
sort(d11, decreasing = TRUE)

[1] 3 3 3 3 3 2 2 2 2 2 1 1 1 1 1

In [24]:
sort(d11, decreasing = FALSE)

[1] 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3

Basic Math functions

In [25]:
x = -23.45671
y = 5.143089

In [26]:
abs(x)

[1] 23.45671

In [27]:
sign(x)

[1] -1

In [28]:
sign(y)

[1] 1

In [29]:
sqrt(25)

[1] 5

In [30]:
round(x, 3)

[1] -23.457

In [31]:
exp(1)

[1] 2.718282

In [32]:
log(100, 10)

[1] 2

In [ ]:
log(100)    #log(100, e)

[1] 4.60517

In [34]:
sin(2 * pi)

[1] -2.449213e-16

In [ ]:
cumsum(1:5)     #1 2 3 4 5

[1]  1  3  6 10 15

In [36]:
cumprod(1:5)

[1]   1   2   6  24 120

In [37]:
factorial(5)

[1] 120

Basic statistical functions

In [38]:
v1 <- c(1,4,5,7,9,13)
v2 <- c(10,37, 53, 68, 81, 118)

In [39]:
min(v1)

[1] 1

In [40]:
max(v1)

[1] 13

In [41]:
mean(v1)

[1] 6.5

In [42]:
var(v1)

[1] 17.5

In [43]:
sd(v1)

[1] 4.1833

In [44]:
cor(v1, v2)

[1] 0.9965388

Logical functions

In [45]:
v1<- c(1,4,6,7,9,13)

In [46]:
v1 == 6

[1] FALSE FALSE  TRUE FALSE FALSE FALSE

In [47]:
which(v1 == 6)

[1] 3

In [48]:
any(v1 > 7)

[1] TRUE

In [49]:
all(v1 <= 7)

[1] FALSE

In [50]:
! v1 == 6

[1]  TRUE  TRUE FALSE  TRUE  TRUE  TRUE

In [51]:
any(v1 > 7) & any(v1 <= 10)

[1] TRUE

In [52]:
any(v1 > 10) | all(v1 <= 10)

[1] TRUE

Matrix

In [53]:
A = matrix(c(1:6), nrow = 2, ncol = 3, byrow = TRUE )
A

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [54]:
dim(A)

[1] 2 3

In [55]:
A[1, 3]

[1] 3

In [56]:
A[1, ]

[1] 1 2 3

In [57]:
A[, 2]

[1] 2 5

In [58]:
A[,c(2,3)]

[,1] [,2]
[1,] 2    3   
[2,] 5    6

In [59]:
A[,-1]

[,1] [,2]
[1,] 2    3   
[2,] 5    6

In [61]:
A[,c(-2, -3)]

[1] 1 4

In [62]:
A[A > 4]

[1] 5 6

In [63]:
A[A%%2 == 0]

[1] 4 2 6

In [65]:
dimnames(A) = list(c("r1","r2"),c("c1","c2","c3"))
A

c1 c2 c3
r1 1  2  3 
r2 4  5  6

In [66]:
A["r1","c2"]

[1] 2

In [67]:
rownames(A) <- c("r10","r20")
colnames(A) <- c("c10","c20","c30")
A

c10 c20 c30
r10 1   2   3  
r20 4   5   6

In [68]:
t(A)

r10 r20
c10 1   4  
c20 2   5  
c30 3   6

In [69]:
B = matrix(c(7,8,9,10), nrow = 2, ncol = 2, byrow = T)
B

[,1] [,2]
[1,] 7     8  
[2,] 9    10

In [70]:
cbind(A,B)

c10 c20 c30     
r10 1   2   3   7  8
r20 4   5   6   9 10

In [71]:
rbind(t(A),B)

r10 r20
c10 1    4 
c20 2    5 
c30 3    6 
    7    8 
    9   10

In [72]:
A[1,3] <- 10
A

c10 c20 c30
r10 1   2   10 
r20 4   5    6

In [73]:
A[A < 4] <- 0
A

c10 c20 c30
r10 0   0   10 
r20 4   5    6

In [74]:
A + 5

c10 c20 c30
r10 5    5  15 
r20 9   10  11

In [76]:
dim(A) <- c(3,2)
A

[,1] [,2]
[1,] 0     5  
[2,] 4    10  
[3,] 0     6

lists

In [77]:
l <- list(1,"a", TRUE, 1+4i,c(1,2,3))
l

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1+4i

[[5]]
[1] 1 2 3

Dataframes

In [80]:
products <- c ("p1", "p2", "p3")
unitprice <- c(20,15,40)
monthlydemand <- c(1500, 2000, 850)
df <- data.frame(products,unitprice, monthlydemand)
df

products unitprice monthlydemand
1 p1       20        1500         
2 p2       15        2000         
3 p3       40         850